### ISSUE TITLE
JavaScript heap out of memory when trying to build on Netlify

### ISSUE THREAD

**Issue by HassanZahirnia** [DecliningLotus/fontsource#705]
### Describe the bug

So when I upgrade the `@fontsource/poppins` from `^4.5.10` to`^5.0.0` my Nuxt project build fails on Netlify and I get a long error which I copied here.

### Steps to Reproduce

Use `@fontsource/poppins` version `5.0.0` and try to deploy a Nuxt project on Netlify.

But specifically the repo I get the issue is: https://github.com/HassanZahirnia/laravel-package-ocean

Which is open source so you can check it out.

### Version

5.0.0

### Additional context

Netlify Build Log:
```
Functions bundling                                            
5:11:55 PM: ────────────────────────────────────────────────────────────────
5:11:55 PM: ​
5:11:55 PM: Packaging Functions from .netlify/functions-internal directory:
5:11:55 PM:  - server/server.mjs
5:11:55 PM: ​
5:11:59 PM: <--- Last few GCs --->
5:11:59 PM: [3320:0x61022d0]    20210 ms: Mark-sweep (reduce) 227.3 (273.0) -> 227.2 (241.2) MB, 30.7 / 0.0 ms  (average mu = 0.887, current mu = 0.198) last resort GC in old space requested
5:11:59 PM: [3320:0x61022d0]    20246 ms: Mark-sweep (reduce) 227.2 (241.2) -> 227.2 (241.2) MB, 35.9 / 0.0 ms  (average mu = 0.780, current mu = 0.001) last resort GC in old space requested
5:11:59 PM: <--- JS stacktrace --->
5:11:59 PM: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
5:11:59 PM:  1: 0xb090e0 node::Abort() [/opt/buildhome/node-deps/node]
5:11:59 PM:  2: 0xa1b70e  [/opt/buildhome/node-deps/node]
5:11:59 PM:  3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/node-deps/node]
5:11:59 PM:  4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/node-deps/node]
5:11:59 PM:  5: 0xe993e5  [/opt/buildhome/node-deps/node]
5:11:59 PM:  6: 0xeabe58 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/buildhome/node-deps/node]
5:11:59 PM:  7: 0xe79bb6 v8::internal::Factory::CodeBuilder::AllocateCode(bool) [/opt/buildhome/node-deps/node]
5:11:59 PM:  8: 0xe7a215 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/opt/buildhome/node-deps/node]
5:11:59 PM:  9: 0xe7ac2e v8::internal::Factory::CodeBuilder::Build() [/opt/buildhome/node-deps/node]
5:11:59 PM: Failed during stage 'building site': Build script returned non-zero exit code: 134 (https://ntl.fyi/exit-code-134)
5:11:59 PM: 10: 0x14c8d8e v8::internal::RegExpMacroAssemblerX64::GetCode(v8::internal::Handle<v8::internal::String>) [/opt/buildhome/node-deps/node]
5:11:59 PM: 11: 0x11b45b9 v8::internal::RegExpCompiler::Assemble(v8::internal::Isolate*, v8::internal::RegExpMacroAssembler*, v8::internal::RegExpNode*, int, v8::internal::Handle<v8::internal::String>) [/opt/buildhome/node-deps/node]
5:11:59 PM: 12: 0x11d2947 v8::internal::RegExpImpl::Compile(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool, unsigned int&) [/opt/buildhome/node-deps/node]
5:11:59 PM: 13: 0x11d30f0 v8::internal::RegExpImpl::CompileIrregexp(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, bool) [/opt/buildhome/node-deps/node]
5:11:59 PM: 14: 0x11d3cee v8::internal::RegExpImpl::IrregexpPrepare(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>) [/opt/buildhome/node-deps/node]
5:11:59 PM: 15: 0x11d3e67 v8::internal::RegExpImpl::IrregexpExec(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::RegExpMatchInfo>, v8::internal::RegExp::ExecQuirks) [/opt/buildhome/node-deps/node]
5:11:59 PM: 16: 0x11f9038 v8::internal::Runtime_RegExpExec(int, unsigned long*, v8::internal::Isolate*) [/opt/buildhome/node-deps/node]
5:11:59 PM: 17: 0x15d9e19  [/opt/buildhome/node-deps/node]
5:11:59 PM: /opt/build-bin/build: line 113:  3320 Aborted                 (core dumped) FORCE_COLOR=1 "$netlify_build_node_bin" "$netlify_build_bin" --cwd="$repository_root" --repositoryRoot="$repository_root" --branch="$branch" --siteId="$site_id" --defaultConfig="$default_config" --baseRelDir="$base_rel_dir" --context="$context" --node-path="$user_node_path" --cachedConfigPath="$cached_netlify_build_config_file" --api-host="$netlify_endpoint" --token="$netlify_token" --build-id="$BUILD_ID" --deploy-id="$DEPLOY_ID" --mode="buildbot" --telemetry="$build_telemetry" --send-status --save-config --statsd.host="$DATADOG_HOST" --statsd.port="$STATSD_PORT" --functions-dist-dir="$functions_dist_dir" --edge-functions-dist-dir="$edge_functions_dist_dir" --cache-dir="$cache_dir" --buildbot-server-socket="$buildbot_server_socket" --framework="$framework" --feature-flags="$feature_flags" --testOpts.silentLingeringProcesses="$SILENT_LINGERING_PROCESSES" --system-log-file="$system_log_file"
5:11:59 PM: Error running command: Build script returned non-zero exit code: 134
5:11:59 PM: Failing build: Failed to build site
```

**Comment by ayuhito** [comment]
I checked whether the font files were bugged out but they seem fine... And your installation seems fine too, although I would maybe try capitalising [this](https://github.com/HassanZahirnia/laravel-package-ocean/blob/c9f05d1a5e12e73f679199cd7a32f33343bed20a/tailwind.config.ts#L15) to "Poppins".

 Does this work locally? If it's only related to Netlify, maybe try making an issue at them because they may have a better idea of what's going on.

**Comment by HassanZahirnia** [comment]
Hey thanks for the quick response ayuhito!

Yeah the build command does work locally without any issues:
![image](https://github.com/fontsource/fontsource/assets/15275787/4b4fbf4e-8322-48a5-8c38-38bbccdbad41)

So I'm highly suspecting this is only happening on Netlify.

See this list of most recent builds, which are successful when `@fontsource/poppins` is on `^4.5.10`
<img width="758" alt="image" src="https://github.com/fontsource/fontsource/assets/15275787/12bcb9fa-6ee2-4957-90e5-9797163666d7">

But as soon as I upgrade to `^5.0.0`, the build fails:
![image](https://github.com/fontsource/fontsource/assets/15275787/be73b2d0-86ea-4ecb-ac68-5e9cee0961ef)

Although you may be right and this could be unrelated to fontsource, but it's kinda interesting why this only happens after the v5 major upgrade...

**Comment by ayuhito** [comment]
I think Fontsource might have some relation, but an out-of-memory error sounds like an infrastructure issue. At least the logs determine there are no configuration issues.

I see you also updated `@types/node` to 20 in that commit. Did you change the node version on Netlify as well?

**Comment by HassanZahirnia** [comment]
No I didn't change anything on Netlify side, but just to be sure I just downgraded the `@types/node` to v18, again getting the same error.

Alright I guess I will try to contact Netlify and relay this issue to them, see what they say.

**Comment by HassanZahirnia** [comment]
Just to give a small update, I'm currently investigating this issue with the Netlify team. I opened public a support ticket [here](https://answers.netlify.com/t/javascript-heap-out-of-memory-when-trying-to-build-a-nuxt-app/93138)

I will let you know when I have a solid answer from them on what the issue might be.

**Comment by ayuhito** [comment]
@HassanZahirnia, out of curiosity, could you update the package to its latest version that was released today? I deployed the changes made to #733 which had some corrupted WOFF files and that _may_ be related if Netlify does some bundling on font files on their end. It may help them with their investigation.

**Comment by HassanZahirnia** [comment]
I just tried updating to `5.0.2` and unfortunately the build still fails ＞﹏＜
![image](https://github.com/fontsource/fontsource/assets/15275787/967336d6-c291-4bb3-9e28-4158a48ec6f1)

**Comment by HassanZahirnia** [comment]
Hey @ayuhito !
I just got a reply from the Netlify support team and it appears the problem was because of a dependency bug on their end.
[Here](https://answers.netlify.com/t/javascript-heap-out-of-memory-when-trying-to-build-a-nuxt-app/93138/14) is the detailed answer from them with a workaround.

I believe we can close this issue, as we can conclude it's not related to `fontsource`. I'm sorry for any inconveniences and taking your time.

Thanks for your great work! 🌸😊

**Comment by ayuhito** [comment]
Awesome! It's always interesting to see how seemingly innocuous things break the ecosystem 😊
